### ISSUE TITLE
mdpopups 2.0 roadmap

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/sublime-markdown-popups#26]
- [x] Require Sublime 3124 and greater for proper functionality.  Get rid of legacy styling. People should be on at least 3124.  If they want to stay on old Sublime builds, they are going lose proper mdpopups CSS.
- [x] There will be a notification on the forum to give plugin developers a chance to update plugins before 2.0 releases.
- [x]  Should use Sublime CSS variables for things like colors in default CSS.  That way they will get colors directly from themes as Sublime will auto-gen things like --background, --purplish, or a theme can define these themselves.  We will rely on themes and Sublime to give us this.
- [x] No longer output CSS for things like .string or .comment etc.  This clutters the CSS class namespace and risks breaking peoples plugin styling if I ever after add new classes.  Instead, developers must use template filters to get the syntax CSS for given classes.
- [x] Provide just a default.css.  No more base and default, just default.  Have one setting to disable default css called `default_style`.  No `default_formatting` **and** `default_style`, but just `default_style`.  They either want to use the default or they can disable it and use their own in a custom mdpopups.css.  Maintaining separate CSS for colors and formatting is annoying.  We actually provide very little color out of the box now and will now use CSS variables that should already be provided by Sublime (--background, --purplish, etc.).  Plugins can still take advantage of syntax style classes, but default CSS will not use those.
- [x] Default styling for admonitions.
- [x] Default styling for kbd.
- [x] Force a monospace font for code blocks.   Can obviously be set to a users specified font via custom user mdpopups.css.
- [x] Upgrade Markdown plugins to the latest.
- [x] Allow toggling of wrapping in code block.
- [x] No more default padding on popups and phantoms (phantoms already don't have padding).  I've come to realize that opinions on padding differ greatly, so let plugins and/or themes (please don't do this themes :() define this.
- [x] Use pymdownx.highlight instead of markdown.extensions.codehilite. Never liked the mock shebangs in CodeHilite as there is never a way to escape them.  I feel this kind of configuration is better left to fences.  We can't really tap into the other features of `highlight`, yet, but maybe in the future.
- [x] Update material theme for docs.
- [x] Need a better way to manage pygments theme preferences with recent changes to CSS handling.
- [x] Drop `mdpopups.font_scale`
- [x] CSS filter should accept any Sublime scope and no longer must it be represented as a CSS class.
- [x] Update documentation.
- [x] Add document spellchecker
- [x] Add changelog to documents

Roadmap subject to change.

**Comment by buildersbrewery** [comment]
* [ ] fix minor issue where [`./st3/mdpopups/st_code_highlight.py`#L197](https://github.com/facelessuser/sublime-markdown-popups/blob/2e8ff03f33ac89b1c13bde282c3fb784070fce2a/st3/mdpopups/st_code_highlight.py#L197) should have been `user_map = self.view.settings().get('mdpopups.sublime_user_lang_map', {})`

**Comment by facelessuser** [comment]
@buildersbrewery 

>  fix minor issue where ./st3/mdpopups/st_code_highlight.py#L197 should have been user_map = self.view.settings().get('mdpopups.sublime_user_lang_map', {})

Why should it be `self.view` instead?  I have no expectation that this setting would be dynamically different per view.  Is there a reason why you think this should change?

> make "mdpopups.use_sublime_highlighter": true the default

I don't plan to get rid of pygments.  The main reason I make it default is the code map right now doesn't cover as much as pygments does.  Also, the map is dependent on the user having those syntaxes installed.  You can render highlighted code that the user doesn't even have that syntax installed.  Ultimately I let the user decide what they want.

>  make separator lines go across the full width of the popup without the indentation on the left

This is cosmetic and subjective to the user.  Ultimately, the user can override this currently via the user override CSS.

If you have any arguments why I think this approach is unfavorable, or if you have other suggestions, feel free to comment.  I am open to suggestions as I move forward with the next release.

**Comment by buildersbrewery** [comment]
@facelessuser

Your current setup ignores:

* project settings
* syntax-specific settings
* buffer settings

`self.view.settings()` would be more specific according to <https://www.sublimetext.com/docs/3/settings.html>, that way even if those have been dynamically changed the plug-in applies them. Targetting the `self.view` also includes the user preferences, so I don't see why it shouldn't be changed. Am I missing undesired side-effects?

**Comment by facelessuser** [comment]
My point is that the language map is a global mapping.  It doesn't make sense, at least not to me, to be syntax specific, project specific, etc.  I'm not against supporting project or view specific options for settings that lend themselves  to that.

Is there a reason you feel this setting would be better suited as a per view setting? Just because it can be doesn't strike me as a valid argument.  I don't think this mapping should be dynamically modified per view.

**Comment by buildersbrewery** [comment]
Your reasoning is correct, it shouldn't be dynamically be modified per view. Should someone choose to do so however, it might not be obvious to them why it doesn't work as expected. Hence, my suggestion.

**Comment by facelessuser** [comment]
> it might not be obvious to them why it doesn't work as expected. Hence, my suggestion.

People try to do stuff all the time that the documentation never even says they can do.  They will always try things I haven't thought about, or don't plan to support.  I'm kinda of the opinion if people do something weird it's on them as long as it doesn't crash the plugin or something like that. In this case it may not work as a user would expect, but it won't throw any exceptions which, in this case, is all I would be concerned about. And I never say in the documentation that this setting is supported per view, or per project, so if someone did this, it would just be them making undocumented assumptions.  I am okay with their assumptions being incorrect :slightly_smiling_face: .

**Comment by facelessuser** [comment]
Moving forward.  Everything I outlined has been completed.  I need to go over everything and make sure there isn't anything else I want to stuff into this.  I'll have to update the docs before the initial release, but I will have a window of time after notifying users on the forum and the official release.

Most likely all I will feature freeze 2.0 soon as I want to get mdpopups 2 out soon as I feel ST3 beta probably isn't too far away from official release (at the very least, the popup API is pretty stable now).

**Comment by facelessuser** [comment]
I'm considering turning on `mdpopups.use_sublime_highlighter` by default moving forward.

And since I recently reworked how CSS is done, I need a better way to allow users to override pygments themes if they decide to go that route.

**Comment by facelessuser** [comment]
I'm thinking maybe I will disable pygments by default, and if the user wants to use pygments, they can add the pygments styling in their `mdpopups.css` file.  People generally prefer the Sublime highlighter, and it may encourage people to update the the sublime code mapping if it is the default styling method.

**Comment by facelessuser** [comment]
It occurred to me that the current css filter that retrieves equivalent CSS for a given scope is locked to very specific textmate scopes, but as we are no longer inserting basic textmate/sublime scopes into the CSS anymore, there isn't necessarily a reason to restrict the CSS filter to things like basic textmate scopes.  So I want to look into possibly expanding it to take any kind of scope you throw at it regardless of complexity.

**Comment by facelessuser** [comment]
@buildersbrewery, I did end up extended hr to full width. I also muted the color a little out of the box.

**Comment by facelessuser** [comment]
All planned things are complete and this is scheduled to drop on June 1st. Closing issue.
